package com.hello.opa.controller;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.hello.opa.domain.Exercise;
import com.hello.opa.domain.User;
import com.hello.opa.repos.ExerciseRepository;
import com.hello.opa.thymeleaf.ExerciseForm;

@Controller
public class MainController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ExerciseRepository exerciseRepository;

//	@GetMapping("/greeting")
//	public String greeting(@RequestParam(name = "name", required = false, defaultValue = "World") String name,
//			Model model) {
//		model.addAttribute("name", name);
//		return "greeting";
//	}

	@GetMapping("/")
	public String greeting(Map<String, Object> model) {
		return "greeting";
	}

	@GetMapping("/main")
	public String main(Model model) {
		Iterable<Exercise> exercises = exerciseRepository.findAll();

		model.addAttribute("exercises", exercises);

		return "main";
	}

	@GetMapping("/addExercise")
    public String addEx(Model model) {
		
		    model.addAttribute("exerciseForm", new ExerciseForm());
		  
        return "addExercise";
    }

	@PostMapping("/addExercise")
	public String add(@AuthenticationPrincipal User user,
			@ModelAttribute(name = "exerciseForm") ExerciseForm exerciseForm, Model model) {

		String title = exerciseForm.getTitle();
		String task = exerciseForm.getTask();
		String answer = exerciseForm.getAnswer();
		Exercise exercise = new Exercise(title, task, user, answer);

		exerciseRepository.save(exercise);

		Iterable<Exercise> exercises = exerciseRepository.findAll();

		model.addAttribute("exercises", exercises);

		return "main";
	}
//	@GetMapping("/add")
//	public String greeting(@RequestParam(name = "name", required = false, defaultValue = "World") String name,
//			Model model) {
//		model.addAttribute("name", name);
//		return "addUser";
//	}

//	@PostMapping("/add")
//	public String add(@RequestParam String name,@RequestParam String email, Map<String, Object> model) {
//		User user = new User(name, email);
//		userRepository.save(user);
//		return "addUser";
//		

	// }
//	@PostMapping("/filter")
//	public String filter(@RequestParam String filter, Map<String, Object> model) {
//		List<User> users = (List<User>) userRepository.findByUsername(filter);
//		((Model) model).addAttribute("users", users);
//		return "filter";
//		
//		
	// }

}